/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public\models\items\varda.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/varda.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Varda.geometry} material={materials['Material.001']} scale={0.024} />
    </group>
  )
}

useGLTF.preload('/varda.glb')
